// Pixel character parts. 32x48 canvas, feet at the bottom. Head rows 10-27, body 28-41, legs 42-47.
// Letters: k outline, h head, b body, y belly, f feet, e ear, i ear inner, m muzzle,
// s spikes, d dark marking, o tail (body color), W white, w white, r red, p pink, a apron, g gold, x hat.
// Pure data; test/sprites.test.js checks row widths.

const BLANK = '................................';

export const BASE = [
  ...Array(10).fill(BLANK),
  '..........kkkkkkkkkkkk..........',
  '........kkhhhhhhhhhhhhkk........',
  '.......khhhhhhhhhhhhhhhhk.......',
  '......khhhhhhhhhhhhhhhhhhk......',
  '.....khhhhhhhhhhhhhhhhhhhhk.....',
  '.....khhhhhhhhhhhhhhhhhhhhk.....',
  '.....khhhhhhhhhhhhhhhhhhhhk.....',
  '.....khhhhhhhhhhhhhhhhhhhhk.....',
  '.....khhhhhhhhhhhhhhhhhhhhk.....',
  '.....khhhhhhhhhhhhhhhhhhhhk.....',
  '.....khhhhhhhhhhhhhhhhhhhhk.....',
  '.....khhhhhhhhhhhhhhhhhhhhk.....',
  '.....khhhhhhhhhhhhhhhhhhhhk.....',
  '.....khhhhhhhhhhhhhhhhhhhhk.....',
  '......khhhhhhhhhhhhhhhhhhk......',
  '.......khhhhhhhhhhhhhhhhk.......',
  '........kkhhhhhhhhhhhhkk........',
  '..........kkkkkkkkkkkk..........',
  '..........kbbbbbbbbbbk..........',
  '.........kbbbbbbbbbbbbk.........',
  '........kbbbbyyyyyybbbbk........',
  '.......kbbbbyyyyyyyybbbbk.......',
  '......kbbbbbyyyyyyyybbbbbk......',
  '....kbkbbbbbyyyyyyyybbbbbkbk....',
  '....kbkbbbbbyyyyyyyybbbbbkbk....',
  '....kbkbbbbbyyyyyyyybbbbbkbk....',
  '....kbkbbbbbyyyyyyyybbbbbkbk....',
  '...kbbkbbbbbyyyyyyyybbbbbkbbk...',
  '...kbbk.kbbbbyyyyyybbbbk.kbbk...',
  '....kk...kbbbbbbbbbbbbk...kk....',
  '..........kkbbbbbbbbkk..........',
  '............kkkkkkkk............',
  '...........kbbbk.kbbbk..........',
  '...........kbbbk.kbbbk..........',
  '...........kbbbk.kbbbk..........',
  '...........kbbbk.kbbbk..........',
  '.........kfffffk.kfffffk........',
  '.........kkkkkkk.kkkkkkk........',
];

// Overlays: { rows, x, y }. Drawn in order; base sits between "behind" and "front" parts.
export const PARTS = {
  earPointL: { x: 4, y: 5, rows: ['.k......', 'khk.....', 'khik....', 'khiik...', 'khiiik..', 'khiiiik.', 'khhhhhhk', '.kkkkkkk'] },
  earPointR: { x: 20, y: 5, rows: ['......k.', '.....khk', '....kihk', '...kiihk', '..kiiihk', '.kiiiihk', 'khhhhhhk', 'kkkkkkk.'] },
  earDroopL: { x: 1, y: 14, rows: ['kkkkk', 'keeek', 'keeek', 'keeek', 'keeek', 'keeek', 'keeek', 'keeek', 'keeek', 'keeek', 'keeek', 'keeek', 'keeek', 'keeek', '.kkk.'] },
  earDroopR: { x: 26, y: 14, rows: ['kkkkk', 'keeek', 'keeek', 'keeek', 'keeek', 'keeek', 'keeek', 'keeek', 'keeek', 'keeek', 'keeek', 'keeek', 'keeek', 'keeek', '.kkk.'] },
  earLongL: { x: 7, y: 0, rows: ['.kkk.', 'khhhk', 'khihk', 'khihk', 'khihk', 'khihk', 'khihk', 'khihk', 'khihk', 'khihk', 'khihk', 'khhhk', 'khhhk', '.kkk.'] },
  earLongR: { x: 20, y: 0, rows: ['.kkk.', 'khhhk', 'khihk', 'khihk', 'khihk', 'khihk', 'khihk', 'khihk', 'khihk', 'khihk', 'khihk', 'khhhk', 'khhhk', '.kkk.'] },
  earRoundL: { x: 4, y: 8, rows: ['.kkkk.', 'khhhhk', 'khiihk', 'khiihk', 'khhhhk', '.kkkk.'] },
  earRoundR: { x: 22, y: 8, rows: ['.kkkk.', 'khhhhk', 'khiihk', 'khiihk', 'khhhhk', '.kkkk.'] },
  muzzle: { x: 10, y: 19, rows: ['..mmmmmmmm..', '.mmmmmmmmmm.', 'mmmmmmmmmmmm', 'mmmmmmmmmmmm', '.mmmmmmmmmm.', '..mmmmmmmm..'] },
  eyeL: { x: 8, y: 13, rows: ['.kkkk.', 'kwwwwk', 'kwwwwk', 'kwkkwk', 'kwkkwk', 'kwwwwk', '.kkkk.'] },
  eyeR: { x: 18, y: 13, rows: ['.kkkk.', 'kwwwwk', 'kwwwwk', 'kwkkwk', 'kwkkwk', 'kwwwwk', '.kkkk.'] },
  lidL: { x: 8, y: 13, rows: ['hhhhhh', 'hhhhhh', 'hhhhhh', 'kkkkkk'] },
  lidR: { x: 18, y: 13, rows: ['hhhhhh', 'hhhhhh', 'hhhhhh', 'kkkkkk'] },
  browSadL: { x: 8, y: 10, rows: ['....kk', '..kk..', 'kk....'] },
  browSadR: { x: 18, y: 10, rows: ['kk....', '..kk..', '....kk'] },
  noseDark: { x: 14, y: 20, rows: ['.kk.', 'kkkk', '.kk.'] },
  nosePink: { x: 14, y: 20, rows: ['.kk.', 'kppk', '.kk.'] },
  mouthNormal: { x: 11, y: 23, rows: ['k........k', '.kkkkkkkk.'] },
  mouthHappy: { x: 11, y: 23, rows: ['kkkkkkkkkk', 'krrrrrrrrk', '.krrrrrrk.', '..kkkkkk..'] },
  mouthSad: { x: 11, y: 23, rows: ['.kkkkkkkk.', 'k........k'] },
  mouthO: { x: 14, y: 23, rows: ['.kk.', 'krrk', 'krrk', '.kk.'] },
  teeth: { x: 13, y: 24, rows: ['kwwkwwk', 'kwwkwwk', '.kkkkk.'] },
  beakGoose: { x: 11, y: 19, rows: ['.kkkkkkkk.', 'kggggggggk', 'kggggggggk', '.kkkkkkkk.', '.kggggggk.', '..kkkkkk..'] },
  beakSmall: { x: 14, y: 20, rows: ['.kk.', 'kggk', '.kk.'] },
  beakLong: { x: 13, y: 19, rows: ['kkkkkk', 'kggggk', '.kggk.', '.kggk.', '.kggk.', '.kggk.', '..kk..'] },
  facePatch: { x: 7, y: 12, rows: ['..wwwwwwwwwwwwww..', '.wwwwwwwwwwwwwwww.', 'wwwwwwwwwwwwwwwwww', 'wwwwwwwwwwwwwwwwww', 'wwwwwwwwwwwwwwwwww', 'wwwwwwwwwwwwwwwwww', 'wwwwwwwwwwwwwwwwww', 'wwwwwwwwwwwwwwwwww', '.wwwwwwwwwwwwwwww.', '..wwwwwwwwwwwwww..'] },
  bowtie: { x: 11, y: 28, rows: ['kk......kk', 'krrkkkkrrk', 'krrrkkrrrk', 'krrkkkkrrk', 'kk......kk'] },
  shell: { x: 2, y: 26, rows: ['........kkkkkkkkkkkk........', '.....kkkddddddddddddkkk.....', '...kkddddddddddddddddddkk...', '..kddddddddddddddddddddddk..', '.kddddddddddddddddddddddddk.', '.kddddddddddddddddddddddddk.', 'kddddddddddddddddddddddddddk', 'kddddddddddddddddddddddddddk', 'kddddddddddddddddddddddddddk', '.kddddddddddddddddddddddddk.', '.kddddddddddddddddddddddddk.', '..kddddddddddddddddddddddk..', '...kkddddddddddddddddddkk...', '.....kkkkkkkkkkkkkkkkkk.....'] },
  whiskerL: { x: 2, y: 20, rows: ['....kk..', 'kkkk....', '........', 'kkkk....', '....kk..'] },
  whiskerR: { x: 22, y: 20, rows: ['..kk....', '....kkkk', '........', '....kkkk', '..kk....'] },
  stripes: { x: 11, y: 11, rows: ['dd..dd..dd', 'dd..dd..dd', 'dd..dd..dd'] },
  mask: { x: 6, y: 13, rows: ['..dddddddddddddddd..', '.dddddddddddddddddd.', 'dddddddddddddddddddd', 'dddddddddddddddddddd', 'dddddddddddddddddddd', '.dddddddddddddddddd.', '..dddddddddddddddd..'] },
  glasses: { x: 6, y: 16, rows: ['kk........kk........kk'] },
  spikes: { x: 3, y: 5, rows: ['...s.....s.....s.....s....', '..sss...sss...sss...sss...', '.sssss.sssss.sssss.sssss..', 'ssssssssssssssssssssssssss', 'ssssssssssssssssssssssssss'] },
  apron: { x: 10, y: 29, rows: ['.kkkkkkkkkk.', 'kaaaaaaaaaak', 'kaaaaaaaaaak', 'kaaaaaaaaaak', 'kaaaaaaaaaak', 'kaaaaaaaaaak', 'kaaaaaaaaaak', '.kkkkkkkkkk.'] },
  strap: { x: 8, y: 26, rows: ['dd............', '.dd...........', '..dd..........', '...dd.........', '....dd........', '.....dd.......', '......dd......', '.......dd.....'] },
  bag: { x: 15, y: 32, rows: ['kkkkkk', 'kxxxxk', 'kxxxxk', 'kxxxxk', 'kkkkkk'] },
  tailBushy: { x: 22, y: 30, rows: ['.......kk.', '.....kkook', '...kkoooWk', '..koooooWk', '..kooooook', '..kkoooook', '....kkkkk.'] },
  tailBig: { x: 24, y: 14, rows: ['..kkkk..', '.kooook.', 'kooooook', 'kooooook', 'kooooook', 'kooooook', 'kooooook', 'kooooook', 'kooooook', 'kooooook', 'kooooook', 'kooooook', 'kooooook', 'kooooook', 'kooooook', 'kooooook', 'kooooook', 'kooooook', '.kooook.', '..kkkk..'] },
  hatDeer: { x: 3, y: 4, rows: ['.........kkkkkkkk.........', '.......kkxxxxxxxxkk.......', '.....kkxxxxxxxxxxxxkk.....', '....kxxxxxxxxxxxxxxxxk....', '...kxxxxxxxxxxxxxxxxxxk...', '..kxxxxxxxxxxxxxxxxxxxxk..', 'kkkkkkkkkkkkkkkkkkkkkkkkkk', 'kxxxxxxxxxxxxxxxxxxxxxxxxk', 'kkkkkkkkkkkkkkkkkkkkkkkkkk'] },
  crest: { x: 12, y: 2, rows: ['k..k..k.', 'kdkkdkkd', '.kdkdkd.', '..kdkd..', '...kk...', '...hh...', '...hh...', '...hh...', '...hh...'] },
  fan: { x: 0, y: 4, rows: [
    '............kkkkkkkk............',
    '.........kkkddddddddkkk.........',
    '.......kkddddkdddkdddddkk.......',
    '.....kkdddddkikikidddddddkk.....',
    '....kdddddddkikikiddddddddk.....',
    '...kdddkdddddkkkkkdddddkdddk....',
    '..kddddkikdddddddddddkikddddk...',
    '..kdddkikikdddddddddkikikdddk...',
    '.kddddkkkkkddddddddddkkkkkdddk..',
    '.kddddddddddddddddddddddddddddk.',
    'kddkdddddddddddddddddddddddkddk.',
    'kdkikdddddddddddddddddddddkikdk.',
    'kkikikdddddddddddddddddddkikikk.',
    'kdkkkddddddddddddddddddddddkkkdk',
    'kddddddddddddddddddddddddddddddk',
    'kddddddddddddddddddddddddddddddk',
    '.kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.'] },
  flatTail: { x: 20, y: 30, rows: ['....kkkkkkk.', '..kkdddddddk', '.kddkdkdkddk', 'kdkdkdkdkddk', 'kddkdkdkdddk', '.kdkdkdkddk.', '..kkkkkkkk..'] },
  hatHard: { x: 4, y: 3, rows: ['.........kkkkkk.........', '.......kkxxxxxxkk.......', '.....kkxxxxxxxxxxkk.....', '....kxxxxxkxxxxxxxxk....', '...kxxxxxxkxxxxxxxxxk...', '..kxxxxxxxkxxxxxxxxxxk..', 'kkkkkkkkkkkkkkkkkkkkkkkk', 'kxxxxxxxxxxxxxxxxxxxxxxk', 'kkkkkkkkkkkkkkkkkkkkkkkk'] },
  hatChef: { x: 8, y: 0, rows: ['...kkkk..kkkk...', '..kwwwwkkwwwwk..', '.kwwwwwwwwwwwwk.', '.kwwwwwwwwwwwwk.', '.kwwwwwwwwwwwwk.', '..kwwwwwwwwwwk..', '...kwwwwwwwwk...', '...kwwwwwwwwk...', '...kwwwwwwwwk...', '...kwwwwwwwwk...', '...kkkkkkkkkk...'] },
};

export const SPECIES = {
  basset:   { label: 'Bart',        h: '#b5773f', b: '#b5773f', y: '#f1dfc0', f: '#f1dfc0', e: '#7a4a22', m: '#f1dfc0', x: '#8b5a2b', behind: ['earDroopL', 'earDroopR'], front: ['muzzle', 'noseDark'], sleepy: true, hat: 'hatDeer' },
  goose:    { label: 'Chef Gaston', h: '#ffffff', b: '#ffffff', y: '#ffffff', f: '#f0842c', g: '#f0842c', a: '#7fd1f5', behind: [], front: ['beakGoose', 'apron'], hat: 'hatChef', beak: true },
  pigeon:   { label: 'Pip',         h: '#6f7a8f', b: '#8e97a8', y: '#aab2c0', f: '#f0842c', g: '#f0842c', d: '#7a4a22', x: '#c58b4a', behind: [], front: ['beakSmall', 'strap', 'bag'], beak: true },
  otter:    { label: 'Otto',        h: '#8a5a3a', b: '#8a5a3a', y: '#d9b98c', f: '#d9b98c', i: '#d9b98c', m: '#d9b98c', o: '#8a5a3a', behind: ['tailBushy'], front: ['earRoundL', 'earRoundR', 'muzzle', 'noseDark', 'whiskerL', 'whiskerR'] },
  squirrel: { label: 'Mrs. Nutley', h: '#c0652d', b: '#c0652d', y: '#f6e2c0', f: '#f6e2c0', i: '#f6b8c8', m: '#f6e2c0', o: '#c0652d', behind: ['tailBig', 'earPointL', 'earPointR'], front: ['muzzle', 'noseDark', 'glasses'] },
  fox:      { label: 'Fox',         h: '#f0842c', b: '#f0842c', y: '#fff2dc', f: '#fff2dc', i: '#fff2dc', m: '#fff2dc', o: '#f0842c', behind: ['tailBushy', 'earPointL', 'earPointR'], front: ['muzzle', 'noseDark'] },
  rabbit:   { label: 'Rabbit',      h: '#c9c6d9', b: '#c9c6d9', y: '#ffffff', f: '#ffffff', i: '#f6b8c8', p: '#f08aa8', behind: ['earLongL', 'earLongR'], front: ['nosePink', 'teeth', 'whiskerL', 'whiskerR'] },
  hedgehog: { label: 'Hedgehog',    h: '#e8caa0', b: '#c99a63', y: '#f5e6cc', f: '#f5e6cc', i: '#f5e6cc', s: '#6f4a2a', behind: ['spikes'], front: ['earRoundL', 'earRoundR', 'noseDark'] },
  cat:      { label: 'Cat',         h: '#f2a33a', b: '#f2a33a', y: '#fff2dc', f: '#fff2dc', i: '#f6b8c8', p: '#f08aa8', d: '#c67a1c', o: '#f2a33a', behind: ['tailBushy', 'earPointL', 'earPointR'], front: ['stripes', 'nosePink', 'whiskerL', 'whiskerR'] },
  heron:    { label: 'Ms. Heron',   h: '#9fb3c8', b: '#8fa3b8', y: '#dfe6ee', f: '#f0842c', g: '#f0842c', behind: [], front: ['beakLong', 'glasses'], beak: true },
  penguin:  { label: 'Mayor Waddlesworth', h: '#2f3342', b: '#2f3342', y: '#ffffff', f: '#f0842c', g: '#f0842c', r: '#e0453b', behind: [], front: ['facePatch', 'beakSmall', 'bowtie'], beak: true },
  turtle:   { label: 'Captain Mabel', h: '#7fb069', b: '#7fb069', y: '#cfe3a8', f: '#cfe3a8', d: '#8b5a2b', behind: ['shell'], front: ['noseDark', 'glasses'] },
  peacock:  { label: 'Priscilla',   h: '#2f9e8f', b: '#2f9e8f', y: '#9fe3d8', f: '#f0842c', g: '#f0842c', d: '#3b6fd6', i: '#ffcc4d', behind: ['fan'], front: ['beakSmall', 'crest'], beak: true },
  beaver:   { label: 'Bruno',       h: '#8a5a3a', b: '#8a5a3a', y: '#d9b98c', f: '#d9b98c', i: '#d9b98c', m: '#d9b98c', d: '#5a3520', x: '#ffcc4d', behind: ['flatTail'], front: ['earRoundL', 'earRoundR', 'muzzle', 'noseDark', 'teeth'], hat: 'hatHard' },
  raccoon:  { label: 'Nibbles',     h: '#a5a5a5', b: '#8e8e8e', y: '#d8d8d8', f: '#d8d8d8', i: '#d8d8d8', d: '#3a3a3a', o: '#8e8e8e', behind: ['tailBushy'], front: ['earRoundL', 'earRoundR', 'mask', 'noseDark'] },
};

export const ALL_PARTS = Object.fromEntries(Object.entries(PARTS).map(([k, v]) => [k, v.rows]));
